species = [
  {
    "binomialName": "Agrostis exarata",
    "commonName": "Spike Bentgrass",
    "speciesType": "Grass",
    "height": 6,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Alopecurus geniculatus",
    "commonName": "Water Foxtail",
    "speciesType": "Grass",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Bromus carinatus",
    "commonName": "California Brome",
    "speciesType": "Grass",
    "height": 0.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Bromus vulgaris",
    "commonName": "Columbia Brome",
    "speciesType": "Grass",
    "height": 1,
    "lightRequirement": "Full Sun-Part Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Danthonia californica",
    "commonName": "California Oatgrass",
    "speciesType": "Grass",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Deschampsia caespitosa",
    "commonName": "Tufted Hairgrass",
    "speciesType": "Grass",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Deschampsia elongata",
    "commonName": "Selnder Hairgrass",
    "speciesType": "Grass",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Elymus glaucus",
    "commonName": "Blue Wildrye",
    "speciesType": "Grass",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Festuca californica",
    "commonName": "California Fescue",
    "speciesType": "Grass",
    "height": 4,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Festuca romeri",
    "commonName": "Roemer's Fescue",
    "speciesType": "Grass",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Glyceria leptostachya",
    "commonName": "Slenderspike Mannagrass",
    "speciesType": "Grass",
    "height": 5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Hordeum brachyantherum",
    "commonName": "Meadow Barley",
    "speciesType": "Grass",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Koeleria macrantha",
    "commonName": "Prairie Junegrass",
    "speciesType": "Grass",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Melica subulata",
    "commonName": "Alaska Oniongrass",
    "speciesType": "Grass",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Poa secunda",
    "commonName": "One-sided Bluegrass",
    "speciesType": "Grass",
    "height": 4,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Torreyochloa pallida ",
    "commonName": "Pale False Mannagrass",
    "speciesType": "Grass",
    "height": 5,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Achillea millefolium",
    "commonName": "Yarrow",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Achlys triphylla",
    "commonName": "Vanilla Leaf",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Adiantum pedatum ssp. aleuticum",
    "commonName": "Western Maidenhair Fern",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Allium acuminatum",
    "commonName": "Tapertip Onion",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Drought Tolerant, Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Allium amplectans",
    "commonName": "Slim-leaf Onion",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Allium cernuum",
    "commonName": "Nodding Onion",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Anaphalis margaritacea",
    "commonName": "Pearly Everlasting",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Aquilegia formosa",
    "commonName": "Western Columbine",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Arctostaphylos uva-ursi",
    "commonName": "Kinnikinnick",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun-Full Shade",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Aruncus dioicus",
    "commonName": "Goat's Beard",
    "speciesType": "Herb",
    "height": 7,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Asarum caudatum",
    "commonName": "Wild Ginger",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Asclepias speciosa",
    "commonName": "Showy Milkweed",
    "speciesType": "Herb",
    "height": 6,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Athyrium filix-femina",
    "commonName": "Lady Fern",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Blechnum spicant",
    "commonName": "Deer Fern",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Brodiaea coronaria",
    "commonName": "Crown Brodiaea",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Brodiaea hyacinthina",
    "commonName": "Fool's Onion",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Camassia leichtlinii",
    "commonName": "Great Camas",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Camassia quamash",
    "commonName": "Common Camas",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Cardamine nuttallii",
    "commonName": "Spring Beauty",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex aperta",
    "commonName": "Columbia Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex aquatilis",
    "commonName": "Water Sedge",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex arcta",
    "commonName": "Northern Cluster Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex densa",
    "commonName": "Dense Sedge",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex deweyana",
    "commonName": "Dewey Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex feta",
    "commonName": "Greensheath Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex leptopoda",
    "commonName": "Taperfruit Sedge",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex obnupta",
    "commonName": "Slough Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Mostly Wetland, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex pachystachya",
    "commonName": "Chamisso Sedge",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Drought Tolerant, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex pellita",
    "commonName": "Woolly Sedge",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Drier Ground, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex rostrata",
    "commonName": "Beaked Sedge",
    "speciesType": "Herb",
    "height": 4,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Wet, Standing Water",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex scoparia",
    "commonName": "Broom Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex stipata",
    "commonName": "Sawbeak Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex tumulicola",
    "commonName": "Foothill Sedge",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex unilateralis",
    "commonName": "One-sided Sedge",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex utriculata",
    "commonName": "Common Beaked Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex vesicaria",
    "commonName": "Bladder Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Carex vulpinoidea",
    "commonName": "Fox Sedge",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Cimicifuga elata",
    "commonName": "Tall Bugbane",
    "speciesType": "Herb",
    "height": 7,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Chamerion angustifolium var. canescens",
    "commonName": "Fireweed",
    "speciesType": "Herb",
    "height": 8,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Clarkia amoena",
    "commonName": "Farewell to Spring",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Clarkia purpurea",
    "commonName": "Farewell to Spring",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Claytonia sibirica",
    "commonName": "Miner's Lettuce",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Collinsia grandiflora",
    "commonName": "Large Blue-Eyed Mary",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Collinsia parviflora",
    "commonName": "Small Blue-Eyed Mary",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Collomia grandiflora",
    "commonName": "Grand Collomia",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Coreopsis tinctoria",
    "commonName": "Golden Tickseed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Corydalis scouleri",
    "commonName": "Scouler's Corydalis",
    "speciesType": "Herb",
    "height": 4,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Cynoglossum grande",
    "commonName": "Pacific Hound's Tongue",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Delphinium trolliifolium",
    "commonName": "Columbian Larkspur",
    "speciesType": "Herb",
    "height": 6,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Epilobium densiflorum",
    "commonName": "Dense-Flowered Willowherb",
    "speciesType": "Herb",
    "height": 3.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Eriophyllum lanatum",
    "commonName": "Oregon Sunshine",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Eschscholzia californica",
    "commonName": "California Poppy",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Dicentra formosa",
    "commonName": "Bleeding Heart",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Dichelostemma congestum",
    "commonName": "Ookow",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Disporum hookeri",
    "commonName": "Hooker's Fairy Bells",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Disporum smithii",
    "commonName": "Smith's Fairybells",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Dodecatheon pulchellum",
    "commonName": "Shooting Star",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Xeric, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Eleocharis palustris",
    "commonName": "Creeping Spike-Rush",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Erigeron speciosus",
    "commonName": "Showy Fleabane",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Erythronium oregonum",
    "commonName": "White Fawn Lily",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Fragaria chiloensis",
    "commonName": "Wild Strawberry",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Fragaria vesca",
    "commonName": "Woodland Strawberry",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Full-Part Sun",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Fragaria virginiana",
    "commonName": "Western Alpine Strawberry",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Fritillaria affinis",
    "commonName": "Checker Lily",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Geranium oreganum",
    "commonName": "Western Geranium",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Geum macrophyllum",
    "commonName": "Largeleaf Avens",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Gilia capitata",
    "commonName": "Bluehead Gilia",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Grindelia integrifolia",
    "commonName": "Gumweed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Helenium autumnale",
    "commonName": "Common Sneezeweed",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Heracleum maximum",
    "commonName": "Cow parsnip",
    "speciesType": "Herb",
    "height": 9,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Heuchera chlorantha",
    "commonName": "Alumroot",
    "speciesType": "Herb",
    "height": 3.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Heuchera micrantha",
    "commonName": "Alumroot",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Hydrophyllum tenuipes",
    "commonName": "Pacific Waterleaf",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Iris douglasiana",
    "commonName": "Douglas Iris",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Iris tenax",
    "commonName": "Oregon Iris",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus acuminatus",
    "commonName": "Tapered Rush",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus balticus",
    "commonName": "Baltic Rush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus effusus",
    "commonName": "Pacific Rush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus ensifolius",
    "commonName": "Dagger-leaved Rush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus nevadensis",
    "commonName": "Sierra Rush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus patens",
    "commonName": "Bluish Rush",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Juncus tenuis",
    "commonName": "Slender Rush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lithrophragma parviflorum",
    "commonName": "Small Flowered Fringecup",
    "speciesType": "Herb",
    "height": 12,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lilium columbianum",
    "commonName": "Columbia Lily",
    "speciesType": "Herb",
    "height": 4,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lomatium dissectum",
    "commonName": "Fernleaf Biscuitroot",
    "speciesType": "Herb",
    "height": 4,
    "lightRequirement": "Full-Part",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lomatium nudicaule",
    "commonName": "Barestem Biscuitroot",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lomatium utriculatum",
    "commonName": "Common Biscuitroot",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, good drainage",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lotus micranthus",
    "commonName": "Deervetch",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lotus purshianus",
    "commonName": "American Bird's-foot Trefoil",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Drought Tolerant, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lupinus bicolor",
    "commonName": "Bi-color Lupine",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lupinus polycarpus",
    "commonName": "Small Flowered Lupine",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full sun",
    "moistureRequirement": "Drought Tolerant, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lupinus polyphyllus",
    "commonName": "Large Leaf Lupine",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lupinus rivularis",
    "commonName": "Riverbank Lupine",
    "speciesType": "Herb",
    "height": 3.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Luzula comosa",
    "commonName": "Woodrush",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lycopus uniflorus",
    "commonName": "Northern Bugleweed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Madia elegans",
    "commonName": "Common Tarweed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Madia gracilis",
    "commonName": "Slender Tarweed",
    "speciesType": "Herb",
    "height": 3.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Micranthes occidentalis",
    "commonName": "Western Mountain Saxifrage",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Micranthes oregana",
    "commonName": "Oregon Saxifrage",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Microsteris gracilis",
    "commonName": "Slender Phlox",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Mimulus guttatus",
    "commonName": "Seep Monkeyflower",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Oxalis oregana",
    "commonName": "Redwood Sorrel",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Penstemon ovatus",
    "commonName": "Broadleaf Penstemon",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Perideridia oregana",
    "commonName": "Oregon Yampah",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Petasites frigidus",
    "commonName": "Coltsfoot",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Phacelia heterophylla",
    "commonName": "Varileaf Phacelia",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Plagiobothrys figuratus",
    "commonName": "Fragrant Popcornflower",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Plagiobothrys scouleri",
    "commonName": "Scouler's Popcornflower",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Plectritis congesta",
    "commonName": "Rosy Plectritis",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Polygonum hydropiperoides",
    "commonName": "Swamp Smartweed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Polypodium glycyrrhiza",
    "commonName": "Licorice Fern",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Potentilla glandulosa",
    "commonName": "Sticky Cinquefoil",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Potentilla gracilis",
    "commonName": "Slender Cinquefoil",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Prunella vulgaris ssp. lanceolata",
    "commonName": "Self Heal",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Pteridium aquilinum",
    "commonName": "Bracken Fern",
    "speciesType": "Herb",
    "height": 4,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ranunculus occidentalis",
    "commonName": "Western Buttercup",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ranunculus orthorhynchus",
    "commonName": "Swamp Buttercup",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rumex salicifolius",
    "commonName": "Willow Dock",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Drought Tolerant, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sagittaria latifolia",
    "commonName": "Wapato",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Semi-aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sanguisorba annua",
    "commonName": "Prairie Burnet",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Satureja douglasii",
    "commonName": "Yerba Buena",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Scirpus microcarpus",
    "commonName": "Small Fruited Bulrush",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Scirpus validus",
    "commonName": "Softstem Bulrush",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet, Aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Scrophularia californica",
    "commonName": "California Figwort",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sedum spathulifolium",
    "commonName": "Stonecrop",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Xeric, Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sidalcea campestris",
    "commonName": "Field Checkermallow",
    "speciesType": "Herb",
    "height": 7,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sidalcea virgata",
    "commonName": "Dwarf Checkermallow",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sisyrinchium idahoense",
    "commonName": "Blue-Eyed Grass",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Smilacina racemosa",
    "commonName": "False Solomon's Seal",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Smilacina stellata",
    "commonName": "Star-Flowered Solomon's Seal",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Solidago canadensis",
    "commonName": "Canada Goldenrod",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Solidago elongata",
    "commonName": "West Coast Goldenrod",
    "speciesType": "Herb",
    "height": 6,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Solidago lepida",
    "commonName": "Western Canada Goldenrod",
    "speciesType": "Herb",
    "height": 5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Drought Tolerant, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sparganium emersum",
    "commonName": "Narrowleaf Burreed",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Wet, Aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Symphyotrichum hallii",
    "commonName": "Hall's Aster",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Symphyotrichum subspicatum",
    "commonName": "Douglas' Aster",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Synthyris reniformis",
    "commonName": "Snow Queen",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Thalictrum occidentale",
    "commonName": "Western Meadowrue",
    "speciesType": "Herb",
    "height": 3,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Tellima grandiflora",
    "commonName": "Fringecup",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Tolmiea menziesii",
    "commonName": "Piggyback Plant",
    "speciesType": "Herb",
    "height": 2.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Trillium chloropetalum",
    "commonName": "Sessile Trillium",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Trillium ovatum",
    "commonName": "Western Trillium",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Triteleia hyacinthina",
    "commonName": "White Brodiaea",
    "speciesType": "Herb",
    "height": 2,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Vancouveria hexandra",
    "commonName": "Inside-Out Flower",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Viola adunca",
    "commonName": "Hookedspur Violet",
    "speciesType": "Herb",
    "height": 0.5,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Viola glabella",
    "commonName": "Yellow Wood Violet",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Viola praemorsa",
    "commonName": "Canary Violet",
    "speciesType": "Herb",
    "height": 1,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Wyethia angustifolia",
    "commonName": "Mule's Ears",
    "speciesType": "Herb",
    "height": 1.5,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Acer circinatum",
    "commonName": "Vine Maple",
    "speciesType": "Shrub",
    "height": 25,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Amerlanchier alnifolia",
    "commonName": "Serviceberry",
    "speciesType": "Shrub",
    "height": 15,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ceanothus sanguineus",
    "commonName": "Redstem Ceanothus",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ceanothus velutinus",
    "commonName": "Mountain Balm",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Cornus sericea",
    "commonName": "Red Osier Dogwood",
    "speciesType": "Shrub",
    "height": 20,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Euonymous occidentalli",
    "commonName": "Western Wahoo",
    "speciesType": "Shrub",
    "height": 12,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moise",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Gaultheria shallon",
    "commonName": "Salal",
    "speciesType": "Shrub",
    "height": 3,
    "lightRequirement": "Full Sun-Full Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Holodiscus discolor",
    "commonName": "Oceanspray",
    "speciesType": "Shrub",
    "height": 13,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Lonicera involucrata",
    "commonName": "Twinberry",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Mahonia aquifolium",
    "commonName": "Tall Oregon Grape",
    "speciesType": "Shrub",
    "height": 6,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Mahonia nervosa",
    "commonName": "Low Oregon Grape",
    "speciesType": "Shrub",
    "height": 2,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Mahonia repens",
    "commonName": "Creeping Oregon Grape",
    "speciesType": "Shrub",
    "height": 1,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Oemleria cerasiformis",
    "commonName": "Indian Plum",
    "speciesType": "Shrub",
    "height": 15,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Oplopanax horridus",
    "commonName": "Devil's Club",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Philadelphus lewisii",
    "commonName": "Mock Orange",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Physocarpus capitatus",
    "commonName": "Ninebark",
    "speciesType": "Shrub",
    "height": 13,
    "lightRequirement": "Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Potentilla fruticosa",
    "commonName": "Bush Cinquefoil",
    "speciesType": "Shrub",
    "height": 4,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Polystichum munitum",
    "commonName": "Sword Fern",
    "speciesType": "Shrub",
    "height": 4,
    "lightRequirement": "Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rhamnus purshiana",
    "commonName": "Cascara",
    "speciesType": "Shrub",
    "height": 30,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rhododendron macrophyllum",
    "commonName": "Pacific Rhododendron",
    "speciesType": "Shrub",
    "height": 36,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rhododendron occidentale",
    "commonName": "Western Azalea",
    "speciesType": "Shrub",
    "height": 13,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ribes divaricatum",
    "commonName": "Black gooseberry",
    "speciesType": "Shrub",
    "height": 7,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Ribes sanguineum",
    "commonName": "Red Flowering Currant",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rosa gymnocarpa",
    "commonName": "Bald-Hip Rose",
    "speciesType": "Shrub",
    "height": 5,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rosa pisocarpa",
    "commonName": "Swamp Rose",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rubus leucodermis",
    "commonName": "Blackcap Raspberry",
    "speciesType": "Shrub",
    "height": 7,
    "lightRequirement": "Full-Part Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rubus parviflorus",
    "commonName": "Thimbleberry",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rubus spectabilis",
    "commonName": "Salmonberry",
    "speciesType": "Shrub",
    "height": 13,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Rubus ursinus",
    "commonName": "Trailing Blackberry",
    "speciesType": "Shrub",
    "height": 16,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix exigua var. columbiana",
    "commonName": "Columbia River Willow",
    "speciesType": "Shrub",
    "height": 20,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix exigua var. sessilifolia",
    "commonName": "Soft-Leaved Willow",
    "speciesType": "Shrub",
    "height": 25,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix hookeriana",
    "commonName": "Hooker's Willow",
    "speciesType": "Shrub",
    "height": 20,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix lasiandra var. lasiandra",
    "commonName": "Pacific Willow",
    "speciesType": "Shrub",
    "height": 40,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix prolixa",
    "commonName": "MacKenzie's Willow",
    "speciesType": "Shrub",
    "height": 30,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix scouleriana",
    "commonName": "Scouler Willow",
    "speciesType": "Shrub",
    "height": 40,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Salix sitchensis",
    "commonName": "Sitka Willow",
    "speciesType": "Shrub",
    "height": 25,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sambucus cerulea",
    "commonName": "Blue Elderberry",
    "speciesType": "Shrub",
    "height": 12,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Sambucus racemosa",
    "commonName": "Red Elderberry",
    "speciesType": "Shrub",
    "height": 20,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Spirea douglasii",
    "commonName": "Douglas Spirea",
    "speciesType": "Shrub",
    "height": 7,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Symphoricarpos albus",
    "commonName": "Snowberry",
    "speciesType": "Shrub",
    "height": 7,
    "lightRequirement": "Full Sun-Full Shade",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Viburnum ellipticum",
    "commonName": "Oregon Viburnum",
    "speciesType": "Shrub",
    "height": 10,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Abies grandis",
    "commonName": "Grand Fir",
    "speciesType": "Tree",
    "height": 260,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Acer macrophyllum",
    "commonName": "Big Leaf Maple",
    "speciesType": "Tree",
    "height": 80,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Alnus incana",
    "commonName": "Mountain Alder",
    "speciesType": "Tree",
    "height": 25,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Alnus rhombifolia",
    "commonName": "White Alder",
    "speciesType": "Tree",
    "height": 65,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Alnus rubra",
    "commonName": "Red Alder",
    "speciesType": "Tree",
    "height": 80,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Arbutus menziesii",
    "commonName": "Pacific Madrone",
    "speciesType": "Tree",
    "height": 50,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Cornus nuttallii",
    "commonName": "Pacific Dogwood",
    "speciesType": "Tree",
    "height": 65,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Crataegus douglasii",
    "commonName": "Black Hawthorn",
    "speciesType": "Tree",
    "height": 33,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Fraxinus latifolia",
    "commonName": "Oregon Ash",
    "speciesType": "Tree",
    "height": 80,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Malus fusca",
    "commonName": "Western Crabapple",
    "speciesType": "Tree",
    "height": 40,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Pinus ponderosa",
    "commonName": "Ponderosa Pine",
    "speciesType": "Tree",
    "height": 200,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Populus trichocarpa",
    "commonName": "Black Cottonwood",
    "speciesType": "Tree",
    "height": 165,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Prunus emarginata",
    "commonName": "Bitter Cherry",
    "speciesType": "Tree",
    "height": 50,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Prunus virginiana",
    "commonName": "Chokecherry",
    "speciesType": "Tree",
    "height": 30,
    "lightRequirement": "Full-Part Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Pseudotsuga menziesii",
    "commonName": "Douglas Fir",
    "speciesType": "Tree",
    "height": 200,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Quercus garryana",
    "commonName": "Oregon White Oak ",
    "speciesType": "Tree",
    "height": 80,
    "lightRequirement": "Full Sun",
    "moistureRequirement": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Thuja plicata",
    "commonName": "Western Red Cedar",
    "speciesType": "Tree",
    "height": 200,
    "lightRequirement": "Part-Full Shade",
    "moistureRequirement": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomialName": "Tsuga heterophylla",
    "commonName": "Western Hemlock",
    "speciesType": "Tree",
    "height": 200,
    "lightRequirement": "Full Sun-Full Shade",
    "moistureRequirement": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  }
 ]

species.each do |species_object|
  species = Species.create!(species_object)
end