species = [
  {
    "binomial_name": "Agrostis exarata",
    "common_name": "Spike Bentgrass",
    "species_type": "Grass",
    "height": 6,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Alopecurus geniculatus",
    "common_name": "Water Foxtail",
    "species_type": "Grass",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Bromus carinatus",
    "common_name": "California Brome",
    "species_type": "Grass",
    "height": 0.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Bromus vulgaris",
    "common_name": "Columbia Brome",
    "species_type": "Grass",
    "height": 1,
    "light": "Full Sun-Part Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Danthonia californica",
    "common_name": "California Oatgrass",
    "species_type": "Grass",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Deschampsia caespitosa",
    "common_name": "Tufted Hairgrass",
    "species_type": "Grass",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Deschampsia elongata",
    "common_name": "Selnder Hairgrass",
    "species_type": "Grass",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Elymus glaucus",
    "common_name": "Blue Wildrye",
    "species_type": "Grass",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Festuca californica",
    "common_name": "California Fescue",
    "species_type": "Grass",
    "height": 4,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Festuca romeri",
    "common_name": "Roemer's Fescue",
    "species_type": "Grass",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Glyceria leptostachya",
    "common_name": "Slenderspike Mannagrass",
    "species_type": "Grass",
    "height": 5,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Hordeum brachyantherum",
    "common_name": "Meadow Barley",
    "species_type": "Grass",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Koeleria macrantha",
    "common_name": "Prairie Junegrass",
    "species_type": "Grass",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Melica subulata",
    "common_name": "Alaska Oniongrass",
    "species_type": "Grass",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Poa secunda",
    "common_name": "One-sided Bluegrass",
    "species_type": "Grass",
    "height": 4,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Torreyochloa pallida ",
    "common_name": "Pale False Mannagrass",
    "species_type": "Grass",
    "height": 5,
    "light": "Part Shade",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Achillea millefolium",
    "common_name": "Yarrow",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Achlys triphylla",
    "common_name": "Vanilla Leaf",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Adiantum pedatum ssp. aleuticum",
    "common_name": "Western Maidenhair Fern",
    "species_type": "Herb",
    "height": 3,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Allium acuminatum",
    "common_name": "Tapertip Onion",
    "species_type": "Herb",
    "height": 1,
    "light": "Full-Part Sun",
    "moisture": "Drought Tolerant, Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Allium amplectans",
    "common_name": "Slim-leaf Onion",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Allium cernuum",
    "common_name": "Nodding Onion",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Anaphalis margaritacea",
    "common_name": "Pearly Everlasting",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Aquilegia formosa",
    "common_name": "Western Columbine",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Arctostaphylos uva-ursi",
    "common_name": "Kinnikinnick",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun-Full Shade",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Aruncus dioicus",
    "common_name": "Goat's Beard",
    "species_type": "Herb",
    "height": 7,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Asarum caudatum",
    "common_name": "Wild Ginger",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Asclepias speciosa",
    "common_name": "Showy Milkweed",
    "species_type": "Herb",
    "height": 6,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Athyrium filix-femina",
    "common_name": "Lady Fern",
    "species_type": "Herb",
    "height": 3,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Blechnum spicant",
    "common_name": "Deer Fern",
    "species_type": "Herb",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Brodiaea coronaria",
    "common_name": "Crown Brodiaea",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Brodiaea hyacinthina",
    "common_name": "Fool's Onion",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Camassia leichtlinii",
    "common_name": "Great Camas",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Camassia quamash",
    "common_name": "Common Camas",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Cardamine nuttallii",
    "common_name": "Spring Beauty",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex aperta",
    "common_name": "Columbia Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex aquatilis",
    "common_name": "Water Sedge",
    "species_type": "Herb",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex arcta",
    "common_name": "Northern Cluster Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex densa",
    "common_name": "Dense Sedge",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex deweyana",
    "common_name": "Dewey Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex feta",
    "common_name": "Greensheath Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex leptopoda",
    "common_name": "Taperfruit Sedge",
    "species_type": "Herb",
    "height": 1,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex obnupta",
    "common_name": "Slough Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Mostly Wetland, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex pachystachya",
    "common_name": "Chamisso Sedge",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Drought Tolerant, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex pellita",
    "common_name": "Woolly Sedge",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Drier Ground, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex rostrata",
    "common_name": "Beaked Sedge",
    "species_type": "Herb",
    "height": 4,
    "light": "Part Shade",
    "moisture": "Wet, Standing Water",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex scoparia",
    "common_name": "Broom Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex stipata",
    "common_name": "Sawbeak Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex tumulicola",
    "common_name": "Foothill Sedge",
    "species_type": "Herb",
    "height": 1,
    "light": "Full-Part Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex unilateralis",
    "common_name": "One-sided Sedge",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex utriculata",
    "common_name": "Common Beaked Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex vesicaria",
    "common_name": "Bladder Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Part Shade",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Carex vulpinoidea",
    "common_name": "Fox Sedge",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Cimicifuga elata",
    "common_name": "Tall Bugbane",
    "species_type": "Herb",
    "height": 7,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Chamerion angustifolium var. canescens",
    "common_name": "Fireweed",
    "species_type": "Herb",
    "height": 8,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Clarkia amoena",
    "common_name": "Farewell to Spring",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Clarkia purpurea",
    "common_name": "Farewell to Spring",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Claytonia sibirica",
    "common_name": "Miner's Lettuce",
    "species_type": "Herb",
    "height": 1,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Collinsia grandiflora",
    "common_name": "Large Blue-Eyed Mary",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Collinsia parviflora",
    "common_name": "Small Blue-Eyed Mary",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Collomia grandiflora",
    "common_name": "Grand Collomia",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Coreopsis tinctoria",
    "common_name": "Golden Tickseed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Corydalis scouleri",
    "common_name": "Scouler's Corydalis",
    "species_type": "Herb",
    "height": 4,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Cynoglossum grande",
    "common_name": "Pacific Hound's Tongue",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Delphinium trolliifolium",
    "common_name": "Columbian Larkspur",
    "species_type": "Herb",
    "height": 6,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Epilobium densiflorum",
    "common_name": "Dense-Flowered Willowherb",
    "species_type": "Herb",
    "height": 3.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Eriophyllum lanatum",
    "common_name": "Oregon Sunshine",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Eschscholzia californica",
    "common_name": "California Poppy",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Dicentra formosa",
    "common_name": "Bleeding Heart",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Dichelostemma congestum",
    "common_name": "Ookow",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Disporum hookeri",
    "common_name": "Hooker's Fairy Bells",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Disporum smithii",
    "common_name": "Smith's Fairybells",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Dodecatheon pulchellum",
    "common_name": "Shooting Star",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Part Shade",
    "moisture": "Xeric, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Eleocharis palustris",
    "common_name": "Creeping Spike-Rush",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Erigeron speciosus",
    "common_name": "Showy Fleabane",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Erythronium oregonum",
    "common_name": "White Fawn Lily",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Fragaria chiloensis",
    "common_name": "Wild Strawberry",
    "species_type": "Herb",
    "height": 1,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Fragaria vesca",
    "common_name": "Woodland Strawberry",
    "species_type": "Herb",
    "height": 1,
    "light": "Part-Full Shade",
    "moisture": "Full-Part Sun",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Fragaria virginiana",
    "common_name": "Western Alpine Strawberry",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full-Part Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Fritillaria affinis",
    "common_name": "Checker Lily",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Geranium oreganum",
    "common_name": "Western Geranium",
    "species_type": "Herb",
    "height": 1,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Geum macrophyllum",
    "common_name": "Largeleaf Avens",
    "species_type": "Herb",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Gilia capitata",
    "common_name": "Bluehead Gilia",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Grindelia integrifolia",
    "common_name": "Gumweed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Helenium autumnale",
    "common_name": "Common Sneezeweed",
    "species_type": "Herb",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Heracleum maximum",
    "common_name": "Cow parsnip",
    "species_type": "Herb",
    "height": 9,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Heuchera chlorantha",
    "common_name": "Alumroot",
    "species_type": "Herb",
    "height": 3.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Heuchera micrantha",
    "common_name": "Alumroot",
    "species_type": "Herb",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Hydrophyllum tenuipes",
    "common_name": "Pacific Waterleaf",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Iris douglasiana",
    "common_name": "Douglas Iris",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Iris tenax",
    "common_name": "Oregon Iris",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus acuminatus",
    "common_name": "Tapered Rush",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus balticus",
    "common_name": "Baltic Rush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus effusus",
    "common_name": "Pacific Rush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus ensifolius",
    "common_name": "Dagger-leaved Rush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus nevadensis",
    "common_name": "Sierra Rush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus patens",
    "common_name": "Bluish Rush",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Juncus tenuis",
    "common_name": "Slender Rush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lithrophragma parviflorum",
    "common_name": "Small Flowered Fringecup",
    "species_type": "Herb",
    "height": 12,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lilium columbianum",
    "common_name": "Columbia Lily",
    "species_type": "Herb",
    "height": 4,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lomatium dissectum",
    "common_name": "Fernleaf Biscuitroot",
    "species_type": "Herb",
    "height": 4,
    "light": "Full-Part",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lomatium nudicaule",
    "common_name": "Barestem Biscuitroot",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lomatium utriculatum",
    "common_name": "Common Biscuitroot",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, good drainage",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lotus micranthus",
    "common_name": "Deervetch",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lotus purshianus",
    "common_name": "American Bird's-foot Trefoil",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Drought Tolerant, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lupinus bicolor",
    "common_name": "Bi-color Lupine",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lupinus polycarpus",
    "common_name": "Small Flowered Lupine",
    "species_type": "Herb",
    "height": 2,
    "light": "Full sun",
    "moisture": "Drought Tolerant, Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lupinus polyphyllus",
    "common_name": "Large Leaf Lupine",
    "species_type": "Herb",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lupinus rivularis",
    "common_name": "Riverbank Lupine",
    "species_type": "Herb",
    "height": 3.5,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Luzula comosa",
    "common_name": "Woodrush",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lycopus uniflorus",
    "common_name": "Northern Bugleweed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Madia elegans",
    "common_name": "Common Tarweed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Madia gracilis",
    "common_name": "Slender Tarweed",
    "species_type": "Herb",
    "height": 3.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Micranthes occidentalis",
    "common_name": "Western Mountain Saxifrage",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Micranthes oregana",
    "common_name": "Oregon Saxifrage",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Microsteris gracilis",
    "common_name": "Slender Phlox",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Mimulus guttatus",
    "common_name": "Seep Monkeyflower",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Oxalis oregana",
    "common_name": "Redwood Sorrel",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Penstemon ovatus",
    "common_name": "Broadleaf Penstemon",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Perideridia oregana",
    "common_name": "Oregon Yampah",
    "species_type": "Herb",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Petasites frigidus",
    "common_name": "Coltsfoot",
    "species_type": "Herb",
    "height": 1,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Phacelia heterophylla",
    "common_name": "Varileaf Phacelia",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Plagiobothrys figuratus",
    "common_name": "Fragrant Popcornflower",
    "species_type": "Herb",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Plagiobothrys scouleri",
    "common_name": "Scouler's Popcornflower",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Plectritis congesta",
    "common_name": "Rosy Plectritis",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Polygonum hydropiperoides",
    "common_name": "Swamp Smartweed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Polypodium glycyrrhiza",
    "common_name": "Licorice Fern",
    "species_type": "Herb",
    "height": 1,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Potentilla glandulosa",
    "common_name": "Sticky Cinquefoil",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Potentilla gracilis",
    "common_name": "Slender Cinquefoil",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Prunella vulgaris ssp. lanceolata",
    "common_name": "Self Heal",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Pteridium aquilinum",
    "common_name": "Bracken Fern",
    "species_type": "Herb",
    "height": 4,
    "light": "Part Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ranunculus occidentalis",
    "common_name": "Western Buttercup",
    "species_type": "Herb",
    "height": 2,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ranunculus orthorhynchus",
    "common_name": "Swamp Buttercup",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rumex salicifolius",
    "common_name": "Willow Dock",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Drought Tolerant, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sagittaria latifolia",
    "common_name": "Wapato",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Semi-aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sanguisorba annua",
    "common_name": "Prairie Burnet",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Satureja douglasii",
    "common_name": "Yerba Buena",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Scirpus microcarpus",
    "common_name": "Small Fruited Bulrush",
    "species_type": "Herb",
    "height": 5,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Scirpus validus",
    "common_name": "Softstem Bulrush",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet, Aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Scrophularia californica",
    "common_name": "California Figwort",
    "species_type": "Herb",
    "height": 3,
    "light": "Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sedum spathulifolium",
    "common_name": "Stonecrop",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full Sun",
    "moisture": "Xeric, Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sidalcea campestris",
    "common_name": "Field Checkermallow",
    "species_type": "Herb",
    "height": 7,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sidalcea virgata",
    "common_name": "Dwarf Checkermallow",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sisyrinchium idahoense",
    "common_name": "Blue-Eyed Grass",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Smilacina racemosa",
    "common_name": "False Solomon's Seal",
    "species_type": "Herb",
    "height": 3,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Smilacina stellata",
    "common_name": "Star-Flowered Solomon's Seal",
    "species_type": "Herb",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Solidago canadensis",
    "common_name": "Canada Goldenrod",
    "species_type": "Herb",
    "height": 5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Solidago elongata",
    "common_name": "West Coast Goldenrod",
    "species_type": "Herb",
    "height": 6,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Solidago lepida",
    "common_name": "Western Canada Goldenrod",
    "species_type": "Herb",
    "height": 5,
    "light": "Full-Part Sun",
    "moisture": "Drought Tolerant, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sparganium emersum",
    "common_name": "Narrowleaf Burreed",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Wet, Aquatic",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Symphyotrichum hallii",
    "common_name": "Hall's Aster",
    "species_type": "Herb",
    "height": 3,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Symphyotrichum subspicatum",
    "common_name": "Douglas' Aster",
    "species_type": "Herb",
    "height": 3,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Synthyris reniformis",
    "common_name": "Snow Queen",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Thalictrum occidentale",
    "common_name": "Western Meadowrue",
    "species_type": "Herb",
    "height": 3,
    "light": "Part-Full Shade",
    "moisture": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Tellima grandiflora",
    "common_name": "Fringecup",
    "species_type": "Herb",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Tolmiea menziesii",
    "common_name": "Piggyback Plant",
    "species_type": "Herb",
    "height": 2.5,
    "light": "Part-Full Shade",
    "moisture": "Moist, Flooding",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Trillium chloropetalum",
    "common_name": "Sessile Trillium",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Trillium ovatum",
    "common_name": "Western Trillium",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Triteleia hyacinthina",
    "common_name": "White Brodiaea",
    "species_type": "Herb",
    "height": 2,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Vancouveria hexandra",
    "common_name": "Inside-Out Flower",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Viola adunca",
    "common_name": "Hookedspur Violet",
    "species_type": "Herb",
    "height": 0.5,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Viola glabella",
    "common_name": "Yellow Wood Violet",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Viola praemorsa",
    "common_name": "Canary Violet",
    "species_type": "Herb",
    "height": 1,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Wyethia angustifolia",
    "common_name": "Mule's Ears",
    "species_type": "Herb",
    "height": 1.5,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Acer circinatum",
    "common_name": "Vine Maple",
    "species_type": "Shrub",
    "height": 25,
    "light": "Part-Full Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Amerlanchier alnifolia",
    "common_name": "Serviceberry",
    "species_type": "Shrub",
    "height": 15,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ceanothus sanguineus",
    "common_name": "Redstem Ceanothus",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ceanothus velutinus",
    "common_name": "Mountain Balm",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Cornus sericea",
    "common_name": "Red Osier Dogwood",
    "species_type": "Shrub",
    "height": 20,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Euonymous occidentalli",
    "common_name": "Western Wahoo",
    "species_type": "Shrub",
    "height": 12,
    "light": "Part-Full Shade",
    "moisture": "Moise",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Gaultheria shallon",
    "common_name": "Salal",
    "species_type": "Shrub",
    "height": 3,
    "light": "Full Sun-Full Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Holodiscus discolor",
    "common_name": "Oceanspray",
    "species_type": "Shrub",
    "height": 13,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Lonicera involucrata",
    "common_name": "Twinberry",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Mahonia aquifolium",
    "common_name": "Tall Oregon Grape",
    "species_type": "Shrub",
    "height": 6,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Mahonia nervosa",
    "common_name": "Low Oregon Grape",
    "species_type": "Shrub",
    "height": 2,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Mahonia repens",
    "common_name": "Creeping Oregon Grape",
    "species_type": "Shrub",
    "height": 1,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Oemleria cerasiformis",
    "common_name": "Indian Plum",
    "species_type": "Shrub",
    "height": 15,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Oplopanax horridus",
    "common_name": "Devil's Club",
    "species_type": "Shrub",
    "height": 10,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Philadelphus lewisii",
    "common_name": "Mock Orange",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Physocarpus capitatus",
    "common_name": "Ninebark",
    "species_type": "Shrub",
    "height": 13,
    "light": "Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Potentilla fruticosa",
    "common_name": "Bush Cinquefoil",
    "species_type": "Shrub",
    "height": 4,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Polystichum munitum",
    "common_name": "Sword Fern",
    "species_type": "Shrub",
    "height": 4,
    "light": "Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rhamnus purshiana",
    "common_name": "Cascara",
    "species_type": "Shrub",
    "height": 30,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rhododendron macrophyllum",
    "common_name": "Pacific Rhododendron",
    "species_type": "Shrub",
    "height": 36,
    "light": "Part-Full Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rhododendron occidentale",
    "common_name": "Western Azalea",
    "species_type": "Shrub",
    "height": 13,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ribes divaricatum",
    "common_name": "Black gooseberry",
    "species_type": "Shrub",
    "height": 7,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Ribes sanguineum",
    "common_name": "Red Flowering Currant",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rosa gymnocarpa",
    "common_name": "Bald-Hip Rose",
    "species_type": "Shrub",
    "height": 5,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rosa pisocarpa",
    "common_name": "Swamp Rose",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rubus leucodermis",
    "common_name": "Blackcap Raspberry",
    "species_type": "Shrub",
    "height": 7,
    "light": "Full-Part Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rubus parviflorus",
    "common_name": "Thimbleberry",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rubus spectabilis",
    "common_name": "Salmonberry",
    "species_type": "Shrub",
    "height": 13,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Rubus ursinus",
    "common_name": "Trailing Blackberry",
    "species_type": "Shrub",
    "height": 16,
    "light": "Full-Part Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix exigua var. columbiana",
    "common_name": "Columbia River Willow",
    "species_type": "Shrub",
    "height": 20,
    "light": "Full-Part Sun",
    "moisture": "Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix exigua var. sessilifolia",
    "common_name": "Soft-Leaved Willow",
    "species_type": "Shrub",
    "height": 25,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix hookeriana",
    "common_name": "Hooker's Willow",
    "species_type": "Shrub",
    "height": 20,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix lasiandra var. lasiandra",
    "common_name": "Pacific Willow",
    "species_type": "Shrub",
    "height": 40,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix prolixa",
    "common_name": "MacKenzie's Willow",
    "species_type": "Shrub",
    "height": 30,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix scouleriana",
    "common_name": "Scouler Willow",
    "species_type": "Shrub",
    "height": 40,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Salix sitchensis",
    "common_name": "Sitka Willow",
    "species_type": "Shrub",
    "height": 25,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sambucus cerulea",
    "common_name": "Blue Elderberry",
    "species_type": "Shrub",
    "height": 12,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Sambucus racemosa",
    "common_name": "Red Elderberry",
    "species_type": "Shrub",
    "height": 20,
    "light": "Part-Full Shade",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Spirea douglasii",
    "common_name": "Douglas Spirea",
    "species_type": "Shrub",
    "height": 7,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Symphoricarpos albus",
    "common_name": "Snowberry",
    "species_type": "Shrub",
    "height": 7,
    "light": "Full Sun-Full Shade",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Viburnum ellipticum",
    "common_name": "Oregon Viburnum",
    "species_type": "Shrub",
    "height": 10,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Abies grandis",
    "common_name": "Grand Fir",
    "species_type": "Tree",
    "height": 260,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Acer macrophyllum",
    "common_name": "Big Leaf Maple",
    "species_type": "Tree",
    "height": 80,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Alnus incana",
    "common_name": "Mountain Alder",
    "species_type": "Tree",
    "height": 25,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Alnus rhombifolia",
    "common_name": "White Alder",
    "species_type": "Tree",
    "height": 65,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Alnus rubra",
    "common_name": "Red Alder",
    "species_type": "Tree",
    "height": 80,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Arbutus menziesii",
    "common_name": "Pacific Madrone",
    "species_type": "Tree",
    "height": 50,
    "light": "Full Sun",
    "moisture": "Dry",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Cornus nuttallii",
    "common_name": "Pacific Dogwood",
    "species_type": "Tree",
    "height": 65,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Crataegus douglasii",
    "common_name": "Black Hawthorn",
    "species_type": "Tree",
    "height": 33,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Fraxinus latifolia",
    "common_name": "Oregon Ash",
    "species_type": "Tree",
    "height": 80,
    "light": "Full Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Malus fusca",
    "common_name": "Western Crabapple",
    "species_type": "Tree",
    "height": 40,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Pinus ponderosa",
    "common_name": "Ponderosa Pine",
    "species_type": "Tree",
    "height": 200,
    "light": "Full Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Populus trichocarpa",
    "common_name": "Black Cottonwood",
    "species_type": "Tree",
    "height": 165,
    "light": "Full-Part Sun",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Prunus emarginata",
    "common_name": "Bitter Cherry",
    "species_type": "Tree",
    "height": 50,
    "light": "Full-Part Sun",
    "moisture": "Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Prunus virginiana",
    "common_name": "Chokecherry",
    "species_type": "Tree",
    "height": 30,
    "light": "Full-Part Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Pseudotsuga menziesii",
    "common_name": "Douglas Fir",
    "species_type": "Tree",
    "height": 200,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Quercus garryana",
    "common_name": "Oregon White Oak ",
    "species_type": "Tree",
    "height": 80,
    "light": "Full Sun",
    "moisture": "Dry, Moist",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Thuja plicata",
    "common_name": "Western Red Cedar",
    "species_type": "Tree",
    "height": 200,
    "light": "Part-Full Shade",
    "moisture": "Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  },
  {
    "binomial_name": "Tsuga heterophylla",
    "common_name": "Western Hemlock",
    "species_type": "Tree",
    "height": 200,
    "light": "Full Sun-Full Shade",
    "moisture": "Dry, Moist, Wet",
    "photo": "",
    "photographer": "Greg Rabourn",
    "acknowledgement": "www.kingcounty.gov/gonative"
  }
 ]

species.each do |species_object|
  species = Species.create!(species_object)
end